#pragma once

#include <ASGE/Application/Application.hpp>
#include <ASGE/Application/ApplicationConfig.hpp>
#include <ASGE/Events/Enums.hpp>
#include <ASGE/Events/Events.hpp>
#include <ASGE/Events/Keycode.hpp>
#include <ASGE/Game/Game.hpp>
#include <ASGE/Core/Graphics/Color.hpp>
#include <ASGE/Video/Graphics/Renderer.hpp>
#include <ASGE/Video/Graphics/Window.hpp>
#include <ASGE/Video/GraphicsBackend.hpp>
#include <ASGE/Core/Logger/Logger.hpp>
#include <ASGE/Core/Time/Time.hpp>
#include <ASGE/Core/Math/Math.hpp>
#include <ASGE/Core/Patterns/Signal.hpp>
#include <ASGE/Core/Concurrent/Thread.hpp>
#include <ASGE/Core/Concurrent/Context.hpp>
#include <ASGE/Core/Concurrent/ThreadPool.hpp>
#include <ASGE/Core/Allocators/LinearAllocator.hpp>
#include <ASGE/Core/Allocators/PoolAllocator.hpp>
#include <ASGE/Core/Allocators/StackAllocator.hpp>
#include <ASGE/Core/Filesystem/Filesystem.hpp>