#include "CppProject.hpp"

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <fstream>
#include <set>
#include <sstream>
#include <system_error>

namespace fs = std::filesystem;

namespace
{

constexpr char const* kGeneratedNote =
    "// Generated by asge-editor and rewritten by \"Update C++ Project\" -- do not edit.\n";

/** @brief inText with every @KEY@ token replaced by its value. */
std::string Fill( std::string inText, std::vector<std::pair<std::string, std::string>> const& inValues )
{
    for ( auto const& [ key, value ] : inValues )
    {
        auto const token = "@" + key + "@";
        for ( auto pos = inText.find( token ); pos != std::string::npos; pos = inText.find( token, pos + value.size() ) )
        {
            inText.replace( pos, token.size(), value );
        }
    }
    return inText;
}

/** @brief inText escaped for use between double quotes in C++ or CMake source. */
std::string Escape( std::string const& inText )
{
    std::string out;
    for ( char c : inText )
    {
        if ( c == '\\' || c == '"' ) out += '\\';
        out += c;
    }
    return out;
}

/** @brief inName reduced to [A-Za-z0-9_] for use as a CMake project/target name. */
std::string TargetName( std::string inName )
{
    for ( char& c : inName )
    {
        if ( !std::isalnum( static_cast<unsigned char>( c ) ) ) c = '_';
    }
    return inName.empty() ? "game" : inName;
}

/** @brief Writes inContent to inPath, creating folders; an existing file is kept unless inOverwrite. */
asge::BoolResult WriteFile( fs::path const& inPath, std::string const& inContent, bool inOverwrite )
{
    std::error_code ec;
    if ( !inOverwrite && fs::exists( inPath, ec ) ) return asge::BoolResult::Ok();

    fs::create_directories( inPath.parent_path(), ec );
    if ( ec ) return asge::BoolResult::Err( ec, inPath.string() );

    std::ofstream out( inPath, std::ios::binary | std::ios::trunc );
    out << inContent;
    if ( !out ) return asge::BoolResult::Err( std::make_error_code( std::errc::io_error ), inPath.string() );
    return asge::BoolResult::Ok();
}

/** @brief Unique C++ identifiers for inScenes, in the same order. */
std::vector<std::string> UniqueNames( std::vector<CppScene> const& inScenes )
{
    std::vector<std::string> names;
    std::set<std::string> used;
    for ( auto const& scene : inScenes )
    {
        auto const name = CppStateName( scene.m_Name );
        auto unique = name;
        for ( int suffix = 2; !used.insert( unique ).second; ++suffix ) unique = name + std::to_string( suffix );
        names.push_back( unique );
    }
    return names;
}

/** @brief inPath relative to inBase when it is strictly inside it, else empty. */
fs::path InsideOf( fs::path const& inPath, fs::path const& inBase )
{
    auto const relative = inPath.lexically_relative( inBase );
    if ( relative.empty() || relative == "." || *relative.begin() == ".." ) return {};
    return relative;
}

/** @brief project_files.cmake: where the project file is, whether it is portable, and what to copy. */
std::string ProjectFilesCmake( CppProjectInput const& inInput )
{
    auto const projectDir = inInput.m_ProjectFile.parent_path();

    bool portable = true;
    std::vector<std::string> items{ inInput.m_ProjectFile.filename().generic_string() };
    auto const addItem = [&]( fs::path const& inPath )
    {
        auto const relative = InsideOf( inPath, projectDir );
        if ( relative.empty() ) { portable = false; return; }

        auto const item = relative.begin()->generic_string();
        if ( std::find( items.begin(), items.end(), item ) == items.end() ) items.push_back( item );
    };
    for ( auto const& scene : inInput.m_Scenes ) addItem( scene.m_Path );
    for ( auto const& mount : inInput.m_MountDirs ) addItem( mount );

    std::ostringstream list;
    for ( auto const& item : items ) list << " \"" << Escape( item ) << "\"";

    return Fill( R"(# Generated by asge-editor and rewritten by "Update C++ Project" -- do not edit.
set(ASGE_PROJECT_FILE "@FILE@")
set(ASGE_PROJECT_DIR "@DIR@")

# ON when every mount and scene lives inside the project folder. Only then can the
# project be copied next to the executable with its relative paths still valid.
set(ASGE_PROJECT_PORTABLE @PORTABLE@)
set(ASGE_PROJECT_COPY_ITEMS@ITEMS@)
)", {
        { "FILE", Escape( inInput.m_ProjectFile.generic_string() ) },
        { "DIR", Escape( projectDir.generic_string() ) },
        { "PORTABLE", portable ? "ON" : "OFF" },
        { "ITEMS", list.str() } } );
}

/** @brief StateId.hpp: one enumerator per scene, in project order. */
std::string StateIdHeader( std::vector<std::string> const& inNames )
{
    std::ostringstream enums;
    for ( auto const& name : inNames ) enums << "    " << name << ",\n";
    return std::string( "#pragma once\n\n" ) + kGeneratedNote + "\nenum class StateId\n{\n" + enums.str() + "};\n";
}

/** @brief SceneState.hpp: the base every scene's state derives from. */
std::string SceneStateHeader()
{
    return std::string( "#pragma once\n\n" ) + kGeneratedNote + R"(
#include <filesystem>
#include <functional>
#include <optional>
#include <string_view>
#include <utility>
#include <vector>

#include <ASGE/ASGE.hpp>

#include "StateId.hpp"

/** @brief What a scene's state needs from the game: the managers it loads through and its scene file. */
struct SceneContext
{
    asge::game::scene::SceneManager& m_Scenes;
    asge::game::asset::AssetManager& m_Assets;
    asge::video::IRenderer&          m_Renderer;
    std::filesystem::path            m_ScenePath;
};

/**
 * @brief Base of every scene's state. Loads its scene on entry, then calls OnSceneLoaded() -- the
 *        place to find widgets by name and connect their callbacks. Each frame Update() calls
 *        OnUpdate() and then hands the game whatever Replace/Push/Pop/Quit requested, so a state
 *        change asked for in OnUpdate() or a callback takes effect the same frame. Connections made
 *        with Connect() are dropped when the state exits.
 */
class SceneState : public asge::game::state::IGameState<StateId>
{
    std::vector<std::function<void()>>                    m_Disconnectors;
    std::optional<asge::game::state::Transition<StateId>> m_Pending;

protected:
    SceneContext m_Context;

    /** @brief Called once the scene is loaded, each time this state is entered. */
    virtual void OnSceneLoaded() {}

    /** @brief Called every frame this state is updated, before a requested state change is handed to the game. */
    virtual void OnUpdate( float, asge::input::InputState const& ) {}

    /** @brief The registry holding this scene's entities. */
    [[nodiscard]] asge::ecs::Registry& GetRegistry() const { return m_Context.m_Scenes.GetRegistry(); }

    /** @brief The entity named inName in the editor (its Name component), or Entity::Null(). */
    [[nodiscard]] asge::ecs::Entity FindByName( std::string_view inName ) const
    {
        for ( auto [ entity, name ] : GetRegistry().View<asge::game::components::Name>() )
        {
            if ( name.get().m_Name == inName ) return entity;
        }
        return asge::ecs::Entity::Null();
    }

    /** @brief The T component of the entity named inName, or nullptr if there is none. */
    template<typename T>
    [[nodiscard]] T* Find( std::string_view inName ) const
    {
        auto const entity = FindByName( inName );
        if ( entity == asge::ecs::Entity::Null() ) return nullptr;

        auto component = GetRegistry().GetComponent<T>( entity );
        return component ? &component.Value().get() : nullptr;
    }

    /** @brief Connects inCallback to inSignal until this state exits. */
    template<typename... Args, typename Callback>
    void Connect( asge::signals::Signal<Args...>& inSignal, Callback&& inCallback )
    {
        auto connection = inSignal.Connect( std::forward<Callback>( inCallback ) );
        m_Disconnectors.push_back( [connection]() mutable { connection.Disconnect(); } );
    }

    /** @brief Asks the game to swap this state for inId's. */
    void Replace( StateId inId ) { m_Pending = { inId, asge::game::state::TransitionKind::Replace }; }

    /** @brief Asks the game to put inId's state on top of this one. */
    void Push( StateId inId ) { m_Pending = { inId, asge::game::state::TransitionKind::Push }; }

    /** @brief Asks the game to leave this state and return to the one below. */
    void Pop() { m_Pending = { StateId{}, asge::game::state::TransitionKind::Pop }; }

    /** @brief Asks the game to quit. */
    void Quit() { m_Pending = { StateId{}, asge::game::state::TransitionKind::Quit }; }

public:
    explicit SceneState( SceneContext inContext ) : m_Context( std::move( inContext ) ) {}

    void OnEnter() override
    {
        if ( auto result = m_Context.m_Scenes.LoadSceneFromFile( m_Context.m_ScenePath ); !result ) result.LogError();
        OnSceneLoaded();
    }

    void OnExit() override
    {
        for ( auto& disconnect : m_Disconnectors ) disconnect();
        m_Disconnectors.clear();
    }

    [[nodiscard]] std::optional<asge::game::state::Transition<StateId>>
    Update( float inDeltaTime, asge::input::InputState const& inInput ) override
    {
        OnUpdate( inDeltaTime, inInput );
        return std::exchange( m_Pending, std::nullopt );
    }

    void Render( asge::video::IRenderer& ) override {}
    void OnSystemEvent( asge::event::SystemEvent const& ) override {}
};
)";
}

/** @brief Game.hpp: the Game subclass that maps a StateId to its scene's state. */
std::string GameHeader()
{
    return std::string( "#pragma once\n\n" ) + kGeneratedNote + R"(
#include <filesystem>
#include <memory>
#include <string_view>

#include <ASGE/ASGE.hpp>

#include "SceneState.hpp"
#include "StateId.hpp"

/** @brief The project file to load: the copy next to the executable if there is one, else the original. */
std::filesystem::path ResolveProjectFile();

/** @brief Application settings for this game: its title and the window size set in the ASGE project. */
asge::ApplicationConfig MakeApplicationConfig();

class ProjectGame final : public asge::game::Game<StateId>
{
    SceneContext MakeContext( std::string_view inSceneStem );

public:
    ProjectGame( asge::video::IRenderer& inRenderer, asge::audio::AudioDevice& inAudioDev );

protected:
    std::unique_ptr<StateType> CreateState( StateId inId ) override;
};
)";
}

/** @brief Game.cpp: loads the project, starts on its main scene's state, and creates every state. */
std::string GameSource(
    std::vector<CppScene> const& inScenes, std::vector<std::string> const& inNames, std::string const& inTitle )
{
    std::ostringstream includes, stems, cases;
    for ( std::size_t i = 0; i < inScenes.size(); ++i )
    {
        includes << "#include \"states/" << inNames[i] << "State.hpp\"\n";
        stems << "    \"" << Escape( inScenes[i].m_Path.stem().string() ) << "\",\n";
        cases << "    case StateId::" << inNames[i] << ": return std::make_unique<" << inNames[i]
              << "State>( MakeContext( kSceneStems[" << i << "] ) );\n";
    }

    return std::string( kGeneratedNote ) + Fill( R"(
#include "Game.hpp"

#include <array>
#include <filesystem>

#include <SDL3/SDL_filesystem.h>

@INCLUDES@
namespace
{

constexpr std::array<std::string_view, @COUNT@> kSceneStems{
@STEMS@};

}

std::filesystem::path ResolveProjectFile()
{
#ifdef ASGE_PROJECT_PORTABLE
    if ( char const* base = SDL_GetBasePath() )
    {
        auto const deployed = std::filesystem::path( base ) / "project" / std::filesystem::path( ASGE_PROJECT_FILE ).filename();
        if ( std::filesystem::exists( deployed ) ) return deployed;
    }
#endif
    return ASGE_PROJECT_FILE;
}

asge::ApplicationConfig MakeApplicationConfig()
{
    asge::ApplicationConfig config{ .s_Title = "@TITLE@" };
    if ( auto project = asge::game::project::LoadProjectFile( ResolveProjectFile() ) )
    {
        if ( project.Value().m_TargetWidth > 0 ) config.s_Width = project.Value().m_TargetWidth;
        if ( project.Value().m_TargetHeight > 0 ) config.s_Height = project.Value().m_TargetHeight;
    }
    return config;
}

ProjectGame::ProjectGame( asge::video::IRenderer& inRenderer, asge::audio::AudioDevice& inAudioDev )
: Game( inRenderer, inAudioDev )
{
    if ( auto result = LoadProject( ResolveProjectFile() ); !result ) result.LogError();

    auto const& project = GetProject();
    std::filesystem::path start = project.m_MainScene;
    if ( start.empty() && !project.m_Scenes.empty() ) start = project.m_Scenes.front();

    auto initial = StateId{};
    for ( std::size_t i = 0; i < kSceneStems.size(); ++i )
    {
        if ( kSceneStems[i] == start.stem().string() ) initial = static_cast<StateId>( i );
    }
    SetInitialState( initial );
}

SceneContext ProjectGame::MakeContext( std::string_view inSceneStem )
{
    std::filesystem::path scenePath;
    for ( auto const& scene : GetProject().m_Scenes )
    {
        if ( scene.stem().string() == inSceneStem ) { scenePath = scene; break; }
    }
    return SceneContext{ m_SceneManager, m_Assets, m_Renderer, scenePath };
}

std::unique_ptr<ProjectGame::StateType> ProjectGame::CreateState( StateId inId )
{
    switch ( inId )
    {
@CASES@    }
    return nullptr;
}
)", { { "INCLUDES", includes.str() }, { "COUNT", std::to_string( inScenes.size() ) },
      { "STEMS", stems.str() }, { "CASES", cases.str() }, { "TITLE", Escape( inTitle ) } } );
}

/** @brief states/<Name>State.hpp: the user-owned state class for one scene. */
std::string StateHeader( std::string const& inName )
{
    return Fill( R"(#pragma once

#include "../SceneState.hpp"

class @NAME@State final : public SceneState
{
public:
    using SceneState::SceneState;

protected:
    void OnSceneLoaded() override;
    void OnUpdate( float inDeltaTime, asge::input::InputState const& inInput ) override;
};
)", { { "NAME", inName } } );
}

/** @brief states/<Name>State.cpp: where a scene's widgets are wired up and its gameplay goes. */
std::string StateSource( std::string const& inName )
{
    return Fill( R"(#include "@NAME@State.hpp"

void @NAME@State::OnSceneLoaded()
{
    // The scene is loaded. Find widgets by the name set in the editor and connect their callbacks:
    //
    //   if ( auto* play = Find<asge::game::components::UIButton>( "Play" ) )
    //       Connect( play->m_OnClick, [this] { Replace( StateId::/* another scene */ ); } );
    //
    // Replace / Push / Pop / Quit request a state change; Connect drops the callback when this state exits.
}

void @NAME@State::OnUpdate( [[maybe_unused]] float inDeltaTime, [[maybe_unused]] asge::input::InputState const& inInput )
{
    // Called every frame, before a state change requested here or by a callback is handed to the game.
}
)", { { "NAME", inName } } );
}

/** @brief CMakeLists.txt: builds the game against the ASGE tree at inAsgeDir. */
std::string CMakeListsText( std::string const& inTarget, fs::path const& inAsgeDir )
{
    return Fill( R"(cmake_minimum_required(VERSION 3.31)
project(@TARGET@ LANGUAGES CXX)

if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "ASGE needs a 64-bit toolchain: in CMake Tools pick an amd64 kit (not x86 or amd64_x86).")
endif()

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include(project_files.cmake)

# TODO(before release): this points at a local ASGE source tree. Replace it with
# find_package(ASGE) or FetchContent once ASGE is installable for game projects.
set(ASGE_SOURCE_DIR "@ASGE@" CACHE PATH "Folder containing ASGE's CMakeLists.txt")
set(ASGE_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ASGE_BUILD_EDITOR OFF CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
add_subdirectory("${ASGE_SOURCE_DIR}" asge)

file(GLOB_RECURSE STATE_SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/states/*.cpp")
add_executable(@TARGET@ main.cpp Game.cpp ${STATE_SOURCES})
target_link_libraries(@TARGET@ PRIVATE ASGE)
target_compile_definitions(@TARGET@ PRIVATE ASGE_PROJECT_FILE="${ASGE_PROJECT_FILE}")
asge_copy_sdl3_runtime(@TARGET@)

# A portable project is copied next to the executable (into project/) after every
# build, so the game runs from its build folder with the project's relative paths intact.
if(ASGE_PROJECT_PORTABLE)
    target_compile_definitions(@TARGET@ PRIVATE ASGE_PROJECT_PORTABLE)
    add_custom_command(TARGET @TARGET@ POST_BUILD
        COMMAND "${CMAKE_COMMAND}" -E make_directory "$<TARGET_FILE_DIR:@TARGET@>/project")
    foreach(item IN LISTS ASGE_PROJECT_COPY_ITEMS)
        if(IS_DIRECTORY "${ASGE_PROJECT_DIR}/${item}")
            add_custom_command(TARGET @TARGET@ POST_BUILD
                COMMAND "${CMAKE_COMMAND}" -E copy_directory
                    "${ASGE_PROJECT_DIR}/${item}" "$<TARGET_FILE_DIR:@TARGET@>/project/${item}")
        else()
            add_custom_command(TARGET @TARGET@ POST_BUILD
                COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                    "${ASGE_PROJECT_DIR}/${item}" "$<TARGET_FILE_DIR:@TARGET@>/project/")
        endif()
    endforeach()
endif()
)", { { "TARGET", inTarget }, { "ASGE", Escape( inAsgeDir.generic_string() ) } } );
}

/** @brief main.cpp: opens the window and runs ProjectGame. */
std::string MainText()
{
    return R"(#include "Game.hpp"

int main( int, char** )
{
    asge::ApplicationConfig const config = MakeApplicationConfig();
    asge::Application<ProjectGame> app( config );
    app.Run();
    return 0;
}
)";
}

/** @brief .vscode/settings.json: tells CMake Tools the CMake project lives in code/ when the project root is opened. */
std::string VSCodeSettings()
{
    return R"({
    "cmake.sourceDirectory": "${workspaceFolder}/code",
    "cmake.buildDirectory": "${workspaceFolder}/code/build"
}
)";
}

/** @brief Writes every generated file, plus each scene's state files where they don't exist yet. */
asge::BoolResult WriteGenerated( CppProjectInput const& inInput )
{
    if ( inInput.m_Scenes.empty() )
    {
        return asge::BoolResult::Err( std::make_error_code( std::errc::invalid_argument ), "the project has no scenes" );
    }

    auto const dir = CppProjectDir( inInput.m_ProjectFile );
    auto const names = UniqueNames( inInput.m_Scenes );

    for ( auto const& [ file, text ] : std::vector<std::pair<std::string, std::string>>{
        { "project_files.cmake", ProjectFilesCmake( inInput ) },
        { "StateId.hpp", StateIdHeader( names ) },
        { "SceneState.hpp", SceneStateHeader() },
        { "Game.hpp", GameHeader() },
        { "Game.cpp", GameSource( inInput.m_Scenes, names, inInput.m_ProjectFile.stem().string() ) } } )
    {
        if ( auto result = WriteFile( dir / file, text, true ); !result ) return result;
    }

    for ( auto const& name : names )
    {
        if ( auto result = WriteFile( dir / "states" / ( name + "State.hpp" ), StateHeader( name ), false ); !result ) return result;
        if ( auto result = WriteFile( dir / "states" / ( name + "State.cpp" ), StateSource( name ), false ); !result ) return result;
    }
    return asge::BoolResult::Ok();
}

}

fs::path CppProjectDir( fs::path const& inProjectFile ) noexcept
{
    return inProjectFile.parent_path() / "code";
}

bool IsCppProjectLinked( fs::path const& inProjectFile ) noexcept
{
    std::error_code ec;
    return fs::exists( CppProjectDir( inProjectFile ) / "CMakeLists.txt", ec );
}

std::string CppTargetName( fs::path const& inProjectFile )
{
    return TargetName( inProjectFile.stem().string() );
}

std::string CppStateName( std::string const& inSceneName )
{
    std::string name;
    bool upper = true;
    for ( char c : inSceneName )
    {
        if ( !std::isalnum( static_cast<unsigned char>( c ) ) ) { upper = true; continue; }
        name += upper ? static_cast<char>( std::toupper( static_cast<unsigned char>( c ) ) ) : c;
        upper = false;
    }

    if ( name.empty() ) return "Scene";
    if ( std::isdigit( static_cast<unsigned char>( name.front() ) ) ) return "Scene" + name;
    return name;
}

asge::BoolResult CreateCppProject( CppProjectInput const& inInput, fs::path const& inAsgeSourceDir ) noexcept
{
    if ( IsCppProjectLinked( inInput.m_ProjectFile ) )
    {
        return asge::BoolResult::Err(
            std::make_error_code( std::errc::file_exists ), CppProjectDir( inInput.m_ProjectFile ).string() );
    }

    auto const dir = CppProjectDir( inInput.m_ProjectFile );
    auto const title = inInput.m_ProjectFile.stem().string();

    if ( auto result = WriteGenerated( inInput ); !result ) return result;
    if ( auto result = WriteFile( dir / "main.cpp", MainText(), false ); !result ) return result;
    if ( auto result = WriteFile( inInput.m_ProjectFile.parent_path() / ".vscode" / "settings.json", VSCodeSettings(), false ); !result ) return result;
    return WriteFile( dir / "CMakeLists.txt", CMakeListsText( CppTargetName( inInput.m_ProjectFile ), inAsgeSourceDir ), false );
}

asge::BoolResult UpdateCppProject( CppProjectInput const& inInput ) noexcept
{
    return WriteGenerated( inInput );
}

bool OpenInVSCode( fs::path const& inFolder ) noexcept
{
    auto const folder = inFolder.string();
    if ( folder.find( '"' ) != std::string::npos ) return false;

#ifdef _WIN32
    constexpr char const* kQuiet = " >nul 2>&1";
#else
    constexpr char const* kQuiet = " >/dev/null 2>&1";
#endif
    return std::system( ( "code \"" + folder + "\"" + kQuiet ).c_str() ) == 0;
}

asge::BoolResult DeleteCppProject( fs::path const& inProjectFile ) noexcept
{
    auto const dir = CppProjectDir( inProjectFile );
    if ( !IsCppProjectLinked( inProjectFile ) )
    {
        return asge::BoolResult::Err( std::make_error_code( std::errc::no_such_file_or_directory ), dir.string() );
    }

    std::error_code ec;
    fs::remove_all( dir, ec );
    if ( ec ) return asge::BoolResult::Err( ec, dir.string() );
    return asge::BoolResult::Ok();
}
