add_subdirectory(Math)
add_subdirectory(Concurrent)
add_subdirectory(Utils)
add_subdirectory(Memory)
add_subdirectory(Configuration)
add_subdirectory(Filesystem)
add_subdirectory(Video)
add_subdirectory(Graphics)
add_subdirectory(ECS)
add_subdirectory(Events)
add_subdirectory(Input)
add_subdirectory(Assets)
add_subdirectory(Game)
add_subdirectory(Components)
add_subdirectory(Scene)
